export default function getHighschools() {


    const licee = [
  "Colegiul Național „Gheorghe Lazăr”",
  "Liceul Internațional Ioanid",
  "Colegiul Național de Informatică „Tudor Vianu”",
  "Colegiul Național „Sfântul Sava”",
  "Liceul Pedagogic „Anastasia Popescu”",
  "Complexul Educațional Laude-Reut",
  "Colegiul Național Bilingv „George Coșbuc”",
  "Colegiul Național „Spiru Haret”",
  "Colegiul Național „Grigore Moisil”",
  "Liceul Teoretic Școala Europeană București",
  "Colegiul Național „Mihai Viteazul”",
  "Colegiul Național „Matei Basarab”",
  "Colegiul Național „Ion Creangă”",
  "Colegiul Național „Gheorghe Șincai”",
  "Liceul Teoretic Școala Mea",
  "Colegiul Național „I.L. Caragiale”",
  "Colegiul Național „Elena Cuza”",
  "Colegiul Național „Iulia Hasdeu”",
  "Liceul Teoretic „Nicolae Iorga”",
  "Liceul Teoretic „Alexandru Ioan Cuza”",
  "Colegiul Național „Cantemir Vodă”",
  "Liceul Teoretic Internațional de Informatică București",
  "Colegiul Național „Mihai Eminescu”",
  "Liceul Româno-Finlandez",
  "Colegiul Economic „Virgil Madgearu”",
  "Liceul Teoretic „Jean Monnet”",
  "Colegiul Național „Ion Neculce”",
  "Colegiul Național „Școala Centrală”",
  "Liceul Teoretic „Genesis College”",
  "Liceul Teoretic Bilingv „Miguel de Cervantes”",
  "Liceul Teoretic Mihai Ionescu",
  "Colegiul Economic „Nicolae Kretzulescu”",
  "Liceul Teoretic Național",
  "Liceul Teoretic „Alexandru Vlahuță”",
  "Liceul Teoretic Waldorf",
  "Colegiul German „Goethe”",
  "Liceul Teoretic „Ion Barbu”",
  "Liceul Teologic Adventist „Ștefan Demetrescu”",
  "Liceul Teologic Baptist „Logos”",
  "Colegiul Romano-Catolic „Sfântul Iosif”",
  "Colegiul Național „Victor Babeș”",
  "Liceul Teoretic „C.A. Rosetti”",
  "Liceul Teoretic „George Călinescu”",
  "Liceul de Coregrafie „Floria Capsali”",
  "Colegiul Național „Octav Onicescu”",
  "Colegiul Național „Tudor Vladimirescu”",
  "Colegiul Național „Emil Racoviță”",
  "Liceul de Arte Plastice „Nicolae Tonitza”",
  "Seminarul Teologic Ortodox",
  "Liceul Teoretic „Ady Endre”",
  "Liceul Teoretic „Constantin Brâncoveanu”",
  "Liceul Teoretic „Eugen Lovinescu”",
  "Liceul Teoretic „Ștefan Odobleja”",
  "Liceul Teoretic „Dante Alighieri”",
  "Colegiul Național de Arte „Dinu Lipatti”",
  "Liceul Teoretic „Marin Preda”",
  "Colegiul Economic „A.D. Xenopol”",
  "Liceul Greco-Catolic „Timotei Cipariu”",
  "Complexul Școlar „Cronos”",
  "Colegiul Național de Muzică „George Enescu”",
  "Liceul Teoretic „Benjamin Franklin”",
  "Liceul Teoretic Bilingv „Ita Wegman”",
  "Liceul Teoretic „Dimitrie Bolintineanu”",
  "Liceul Teoretic „Mihail Sadoveanu”",
  "Colegiul Național „Aurel Vlaicu”",
  "Liceul Teoretic „Nichita Stănescu”",
  "Liceul Teoretic „Decebal”",
  "Colegiul Tehnologic „Grigore Cerchez”",
  "Liceul Teoretic „Lucian Blaga”",
  "Colegiul Economic „Costin C. Kirițescu”",
  "Liceul Teoretic „Dr. Mioara Mincu”",
  "Liceul cu Program Sportiv „Mircea Eliade”",
  "Liceul Teoretic „Traian”",
  "Liceul Teologic Penticostal „Emanuel”",
  "Colegiul Tehnic „Anghel Saligny”",
  "Colegiul Tehnic de Arhitectură și Lucrări Publice „Ioan N. Socolescu”",
  "Colegiul Tehnic Energetic",
  "Liceul „Dimitrie Paciurea”",
  "Colegiul Tehnic Feroviar „Mihai I”",
  "Colegiul Tehnic „Petru Maior”",
  "Colegiul Tehnic de Poștă și Telecomunicații „Gheorghe Airinei”",
  "Liceul Economic Nr. 1",
  "Liceul Tehnologic „Sf. Antim Ivireanu”",
  "Liceul Teoretic „Victoria”",
  "Liceul Tehnologic „Elie Radu”",
  "Liceul Teoretic „Atlas”",
  "Colegiul Economic „Hermes”",
  "Colegiul Tehnic Mecanic „Grivița”",
  "Liceul Teoretic „Hyperion”",
  "Liceul Tehnologic „Petru Poni”",
  "Liceul Teoretic Bulgar „Hristo Botev”",
  "Colegiul Tehnic „Iuliu Maniu”",
  "Liceul Tehnologic „Constantin Brâncuși”",
  "Colegiul Tehnic „Mircea cel Bătrân”",
  "Colegiul Tehnic „Dinicu Golescu”",
  "Colegiul Tehnic de Aeronautică „Henri Coandă”",
  "Colegiul Tehnic „Gheorghe Asachi”",
  "Colegiul Economic „Viilor”",
  "Liceul Tehnologic de Metrologie „Traian Vuia”",
  "Colegiul Tehnic „Mihai Bravu”",
  "Liceul Tehnologic „Dimitrie Gusti”",
  "Colegiul Tehnic „Costin D. Nenițescu”",
  "Liceul Tehnologic „Nikola Tesla”",
  "Colegiul Tehnic „Edmond Nicolau”",
  "Liceul Tehnologic „Dacia”",
  "Colegiul Tehnic de Industrie Alimentară „Dumitru Motoc”",
  "Colegiul UCECOM „Spiru Haret”",
  "Colegiul Tehnic „Media”",
  "Liceul Tehnologic „Sfântul Pantelimon”",
  "Colegiul Tehnologic „Viaceslav Harnaj”",
  "Liceul „Profesia”",
  "Liceul FEG",
  "Liceul Tehnologic „Dragomir Hurmuzescu”",
  "Liceul Tehnologic Theodor Pallady",
  "Colegiul Tehnic „Carol I”",
  "Colegiul Tehnic „Dimitrie Leonida”",
  "Liceul Tehnologic „Ion I.C. Brătianu”",
  "Liceul Particular „Onicescu-Mihoc”",
  "Liceul Tehnologic Special „Regina Elisabeta”",
  "Liceul Tehnologic Special nr. 3",
];

    return [...licee, '*Învǎțǎmânt Gimazial', '*Învǎțǎmânt Universitar']
}